version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  # web:
  #   build: ./app
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - ./app/:/usr/src/app/
  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - ./.env.dev
  # django:
  #   build: ./app
  #   depends_on:
  #     - db
  #   restart: always
  #   env_file:
  #     - ./.env.dev
  #   volumes:
  #     - static:/app/static
  #     - media:/app/media
  #     - nginx_conf:/app/nginx/
  #   entrypoint: ./entrypoint.sh

  db:
      image: postgres:15
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      env_file:
      - ./.env.dev
      # environment:
      #   - POSTGRES_USER=hello_django
      #   - POSTGRES_PASSWORD=hello_django
      #   - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data: