version: '3.8'

services:
  django:
    #image: ollyko/skillfactory:django-on-docker_django
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: django
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - .:/home/app/web
    expose:
    - 8000
    environment:
     - DJANGO_SUPERUSER_PASSWORD="123123"
     - DJANGO_SUPERUSER_USERNAME="admin"
    depends_on:
      - postgres
  
  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
    - POSTGRES_USER=hello_django
    - POSTGRES_PASSWORD=hello_django
    - POSTGRES_DB=hello_django
    restart: unless-stopped

  nginx:
    image: ollyko/skillfactory:django-on-docker_nginx
    #build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume:
  media_volume: