version: '3.8'

services:
  postgres:
    image: postgres:alpine
    user: postgres
    container_name: postgres_container
    environment:
    - POSTGRES_USER=hello_django
    - POSTGRES_PASSWORD=hello_django
    - POSTGRES_DB=hello_django
    - PGUSER=postgres
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER $$POSTGRES_DB"]
        interval: 30s
        timeout: 60s
        retries: 5
        start_period: 80s

  django:
    image: ollyko/skillfactory:django-on-docker_django
    #build:
    #  context: ./app
    # dockerfile: Dockerfile
    container_name: django
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - .:/home/app/
    expose:
    - 8000
    environment:
      DJANGO_SUPERUSER_PASSWORD: "123321"
      DJANGO_SUPERUSER_EMAIL: "admin@example.com"
      DJANGO_SUPERUSER_USERNAME: "admin"
      DB_ENGINE: "django.db.backends.postgresql"
      DB_NAME: "hello_django"
      POSTGRES_USER: "hello_django"
      POSTGRES_PASSWORD: "hello_django"
      DB_HOST: "postgres"
      DB_PORT: "5432"
    depends_on:
    - postgres

  nginx:
    image: ollyko/skillfactory:django-on-docker_nginx
    #build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - django

volumes:
  static_volume:
  media_volume:

