version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
    - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
    - ./.env.prod.db

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web  
  #django:
    #build: ./app
    #depends_on:
    #  - db
    #restart: always
    #env_file:
    #  - ./.env.prod
    #volumes:
      #- static:/app/static
      #- media:/app/media
      #- nginx_conf:/app/nginx/
    #entrypoint: ./entrypoint.sh

  

volumes:
  postgres_data:
  static_volume:
  media_volume: